### ISSUE TITLE
Issue with loading queues (invalid workflow against zod schema) validation error 

### ISSUE THREAD

**Issue by BrechtCorbeel** [pkpkTech/ComfyUI-SaveQueues#3]
I am leaving this here in case someone needs it:

https://github.com/comfyanonymous/ComfyUI/issues/4627

> ok so I had badly converted utf-8 characters in my prompts causing this issue:

if you want it solved run this script I created to solve the issue:

```
import json
import codecs

# Load the JSON file
with open('J:\\brech\\Documents\\after error2.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

# Function to fix encoding
def fix_encoding(text):
    try:
        # Decode the text using the wrong encoding and re-encode it correctly
        return text.encode('latin1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        # If there's an issue, return the original text
        return text

# Fix encoding for the 'populated_text' key
if 'populated_text' in data:
    data['populated_text'] = fix_encoding(data['populated_text'])

# Save the corrected JSON back to the file
with open('J:\\brech\\Documents\\your_file_fixed.json', 'w', encoding='utf-8') as file:
    json.dump(data, file, ensure_ascii=False, indent=4)

print("File encoding fixed and saved as 'your_file_fixed.json'")
```

**Comment by Whitespidee88** [comment]
How do i add this in script?

**Comment by BrechtCorbeel** [comment]
> How do i add this in script?

You need to run the program and then run it over your workflow, depending on wether this is your issue, make sure to backup your file as this is permanent.

**Comment by Whitespidee88** [comment]
Its not working. I tried extracting meta data from the image file to understand the workflow , I'm currently new and learning comfy. Your assistance will be a great help.
[03dc2b31-a43d-4fae-8929-823ba5142360.json](https://github.com/user-attachments/files/17678381/03dc2b31-a43d-4fae-8929-823ba5142360.json)
